[config]
skip_core_tasks = true

[tasks.fmt]
command = "cargo"
args = ["fmt"]

[tasks.check]
command = "cargo"
args = ["check"]
dependencies = ["fmt"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["check"]

[tasks.run]
command = "cargo"
args = ["run"]
dependencies = ["check"]

[tasks.relaese]
command = "cargo"
args = ["build", "-r"]
dependencies = ["check"]

[tasks.task_test]
windows_alias = "windows_task_test"
alias = "linux_task_test"

[tasks.linux_task_test]
script = '''
echo "task can run!"
'''

[tasks.windows_task_test]
command = "cmd"
args = ["/c", "echo", "task can run!"]
